WIDTH = 1900
HEIGHT = 1000
TITLE = "test"

CHARACTER_SCAILING = 2

DEFAULT_DAMPNING = 1.0

# player constants that will be implemented
# into pymunk physics engine
PLAYER_ACCELERATION = 6000
PLAYER_DEACCELERATION = 0.02
PLAYER_MASS = 20
PLAYER_FRICTION = 0.2
PLAYER_MAX_SPEED = 260
PLAYER_DAMPNING = 0.58
PLAYER_MINING_LASER_DAMAGE = 1

# meteor constants settings for physics engine to use
METOR_MAX_SPEED = 300000
METOR_MIN_SPEEED = 100000
METEOR_MASS = 0.2
METEOR_FRICTION = 0.8
METEOR_HEALTH_CONSTANT = 0.2
ENEMY_SCALEING = 2



MAX_SPEED = 6000

MAX_SPAWN_TIME = 0.001